spring:
  application:
      name: positions
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/positions
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
server:
  servlet:
    context-path: /api
